version: "2"
services:
  mapseed:
    image: 3dwardsharp/ecotopia-today-mapseed
    build: ./
    # restart: always
    env_file: .env
    expose:
      - 8010
    ports: 
      - "8010:8010"
    depends_on:
      - pg
    # volumes:
      # - ./.env:/api/src/.env
      # - /home/core/api_static:/api/static
  # web:
  #   image: 3dwardsharp/nginx-certbot
  #   # restart: always
  #   volumes:
  #     # - /home/core/letsencrypt:/etc/letsencrypt
  #     - ./nginx.template:/etc/nginx/conf.d/nginx.template
  #   ports:
  #     # - "80:80"
  #     # - "443:443"
  #   environment:
  #     - BASE_SERVER=mapseed.ecotopia.today
  #     - ADMIN_SERVER=mapseedadmin.ecotopia.today
  #   command: /bin/bash -c "cron && envsubst < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  pg:
    image: mdillon/postgis:9.6-alpine
    # restart: always
    env_file: .env
    ports:
      - "5432:5432"
    # volumes:
      # - /home/core/pgdata:/var/lib/postgresql/data
